name: Check for new releases

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up shell environment
        run: sudo apt-get update && sudo apt-get install -y curl wget tar

      - name: Check for new releases
        run: |
          bash scripts/check_releases.sh

      - name: Commit changes
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update to latest release"
          git push
